project:
  type: website
  output-dir: docs

website:
  title: "YOUR NAME"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Marketing Analytics"
        href: marketing-analytics.qmd
      - text: "Strategic Marketing"
        href: strategic-marketing.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: [flatly, theme.scss]
    toc: true

